"""
NJCAA Regional Baseball + Softball Scraper
Scrapes per-team batting stats from all 6 NJCAA regional sites.

Covers both sports — identical 19-column format:
  # | Name | Yr | Pos | g | ab | r | h | 2b | 3b | hr | rbi | bb | k | sb | cs | avg | obp | slg

Regions:
  r2  : region2athletics.com       (sball: 16, bsb: 19)
  r5  : njcaaregion5.com           (sball: 17, bsb: 26)
  r14 : njcaaregion14.com          (sball: 15, bsb: 13)
  r15 : region15athletics.com      (sball:  5, bsb: 13)
  r19 : njcaaregion19.com          (sball: 18, bsb: 20)
  r24 : njcaaregion24.com          (sball: 19, bsb: 20)
Total: sball=90, bsb=111

Team slugs loaded from njcaa_regional_baseball_teams.json (generated by slug-discovery agent).
If the JSON doesn't exist or is missing a region, falls back to dynamic listing-page discovery.

Usage:
  python3 njcaa_regional_baseball_scraper.py --sport sball
  python3 njcaa_regional_baseball_scraper.py --sport bsb
  python3 njcaa_regional_baseball_scraper.py            # both sports
  python3 njcaa_regional_baseball_scraper.py --region r5 --sport sball
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

import httpx
import psycopg
from bs4 import BeautifulSoup

sys.path.insert(0, os.path.dirname(__file__))
from config import DB_CONFIG

# ── Config ─────────────────────────────────────────────────────────────────���──

SEASONS = {
    "sball": "2024-25",
    "bsb":   "2024-25",
}

CRAWL_DELAY  = 4   # seconds between team requests
REGION_DELAY = 8   # extra seconds when switching regions

TEAMS_JSON = Path(__file__).parent / "njcaa_regional_baseball_teams.json"

REGIONS = {
    "r2":  "https://region2athletics.com",
    "r5":  "https://njcaaregion5.com",
    "r14": "https://njcaaregion14.com",
    "r15": "https://region15athletics.com",
    "r19": "https://njcaaregion19.com",
    "r24": "https://njcaaregion24.com",
}

BROWSER_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/123.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
}


# ── DB Schema ─────────────────────────────────────────────────────────────────

CREATE_TEAMS = """
CREATE TABLE IF NOT EXISTS njcaa_reg_baseball_teams (
    id       SERIAL PRIMARY KEY,
    region   TEXT NOT NULL,
    sport    TEXT NOT NULL,    -- 'sball' or 'bsb'
    slug     TEXT NOT NULL,
    name     TEXT,
    base_url TEXT NOT NULL,
    season   TEXT NOT NULL,
    UNIQUE (region, sport, slug, season)
);
"""

CREATE_PLAYERS = """
CREATE TABLE IF NOT EXISTS njcaa_reg_baseball_players (
    id         SERIAL PRIMARY KEY,
    team_id    INT  NOT NULL REFERENCES njcaa_reg_baseball_teams(id),
    jersey     TEXT,
    full_name  TEXT NOT NULL,
    position   TEXT,
    class_year TEXT,
    UNIQUE (team_id, full_name)
);
"""

CREATE_STATS = """
CREATE TABLE IF NOT EXISTS njcaa_reg_baseball_stats (
    id        SERIAL PRIMARY KEY,
    player_id INT  NOT NULL REFERENCES njcaa_reg_baseball_players(id),
    season    TEXT NOT NULL,
    g         INT,
    ab        INT,
    r         INT,
    h         INT,
    doubles   INT,
    triples   INT,
    hr        INT,
    rbi       INT,
    bb        INT,
    k         INT,
    sb        INT,
    cs        INT,
    avg       NUMERIC(6,4),
    obp       NUMERIC(6,4),
    slg       NUMERIC(6,4),
    -- computed
    ops       NUMERIC(6,4),   -- obp + slg
    UNIQUE (player_id, season)
);
"""


def ensure_schema(conn):
    conn.execute(CREATE_TEAMS)
    conn.execute(CREATE_PLAYERS)
    conn.execute(CREATE_STATS)
    conn.commit()


# ── HTTP ──────────────────────────────────────────────────────────────────────

def fetch(url: str, base: str, referer: str, retries: int = 3) -> httpx.Response | None:
    hdrs = {**BROWSER_HEADERS, "Origin": base, "Referer": referer}
    for attempt in range(retries):
        try:
            r = httpx.get(url, headers=hdrs, timeout=20, follow_redirects=True)
            if r.status_code == 202 and len(r.content) < 5000:
                wait = 90 if attempt == 0 else 120
                print(f"    [WAF] waiting {wait}s...")
                time.sleep(wait)
                continue
            return r
        except Exception as e:
            print(f"    [err] {url}: {e}")
            time.sleep(10)
    return None


def discover_slugs(base: str, sport: str, season: str) -> list[str]:
    """Try to fetch team listing page and extract slugs. Returns [] on WAF block."""
    list_url = f"{base}/sports/{sport}/{season}/teams"
    nav_hdrs = {
        "User-Agent": BROWSER_HEADERS["User-Agent"],
        "Accept": "text/html,application/xhtml+xml,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "none",
    }
    try:
        r = httpx.get(list_url, headers=nav_hdrs, timeout=20, follow_redirects=True)
        if r.status_code == 202 and len(r.content) < 5000:
            return []
        if r.status_code != 200:
            return []
        soup = BeautifulSoup(r.text, "html.parser")
        links = [
            a["href"] for a in soup.find_all("a", href=True)
            if f"/sports/{sport}/{season}/teams/" in a["href"]
            and not a["href"].rstrip("/").endswith("/teams")
        ]
        return list(dict.fromkeys(
            h.split("/teams/")[1].split("?")[0].split("/")[0]
            for h in links
            if h.split("/teams/")[1].split("?")[0].split("/")[0]
        ))
    except Exception:
        return []


# ── Parsing ───────────────────────────────────────────────────────────────────

def _dash_or_int(v: str | None) -> int | None:
    if not v or v.strip() in ("-", "", "—"):
        return None
    try:
        return int(str(v).replace(",", "").strip())
    except ValueError:
        return None


def _stat_pct(v: str | None) -> float | None:
    """Parse batting avg like '.395' or '0.395' → stored as 0-1."""
    if not v or v.strip() in ("-", "", "—"):
        return None
    try:
        return round(float(str(v).strip()), 4)
    except ValueError:
        return None


def parse_batting_table(html: str) -> list[dict]:
    """
    Parse PrestoSports baseball/softball batting table.

    Fixed column layout (confirmed across all sports/categories):
      0:# 1:Name 2:Yr 3:Pos 4:g 5:ab 6:r 7:h 8:2b 9:3b
      10:hr 11:rbi 12:bb 13:k 14:sb 15:cs 16:avg 17:obp 18:slg
    """
    soup = BeautifulSoup(html, "html.parser")
    table = soup.find("table")
    if not table:
        return []

    thead = table.find("thead")
    if not thead:
        return []

    # Detect column positions from headers (lowercase)
    raw_hdrs = [th.get_text(strip=True).lower() for th in thead.find_all(["th", "td"])]

    def ci(names: list[str], default: int) -> int:
        for n in names:
            for i, h in enumerate(raw_hdrs):
                if h == n:
                    return i
        return default

    C_JERSEY = ci(["#", "no", "num"], 0)
    C_NAME   = ci(["name", "player"], 1)
    C_YR     = ci(["yr", "cl", "class", "year"], 2)
    C_POS    = ci(["pos", "position"], 3)
    C_G      = ci(["g", "gp"], 4)
    C_AB     = ci(["ab"], 5)
    C_R      = ci(["r"], 6)
    C_H      = ci(["h"], 7)
    C_2B     = ci(["2b"], 8)
    C_3B     = ci(["3b"], 9)
    C_HR     = ci(["hr"], 10)
    C_RBI    = ci(["rbi"], 11)
    C_BB     = ci(["bb"], 12)
    C_K      = ci(["k", "so"], 13)
    C_SB     = ci(["sb"], 14)
    C_CS     = ci(["cs"], 15)
    C_AVG    = ci(["avg", "ba"], 16)
    C_OBP    = ci(["obp"], 17)
    C_SLG    = ci(["slg"], 18)

    rows = []
    tbody = table.find("tbody") or table
    for tr in tbody.find_all("tr"):
        cells = tr.find_all(["td", "th"])
        if len(cells) < 10:
            continue

        def cell(i: int) -> str:
            return " ".join(cells[i].get_text(strip=True).split()) if i < len(cells) else ""

        name_raw = cell(C_NAME)
        if not name_raw or name_raw.lower() in ("name", "player", "totals", "total"):
            continue
        name = " ".join(name_raw.split())

        avg = _stat_pct(cell(C_AVG))
        obp = _stat_pct(cell(C_OBP))
        slg = _stat_pct(cell(C_SLG))
        ops = round(obp + slg, 4) if obp is not None and slg is not None else None

        rows.append({
            "name":    name,
            "jersey":  cell(C_JERSEY) or None,
            "pos":     cell(C_POS) or None,
            "cl":      cell(C_YR) or None,
            "g":       _dash_or_int(cell(C_G)),
            "ab":      _dash_or_int(cell(C_AB)),
            "r":       _dash_or_int(cell(C_R)),
            "h":       _dash_or_int(cell(C_H)),
            "doubles": _dash_or_int(cell(C_2B)),
            "triples": _dash_or_int(cell(C_3B)),
            "hr":      _dash_or_int(cell(C_HR)),
            "rbi":     _dash_or_int(cell(C_RBI)),
            "bb":      _dash_or_int(cell(C_BB)),
            "k":       _dash_or_int(cell(C_K)),
            "sb":      _dash_or_int(cell(C_SB)),
            "cs":      _dash_or_int(cell(C_CS)),
            "avg":     avg,
            "obp":     obp,
            "slg":     slg,
            "ops":     ops,
        })
    return rows


# ── DB Writes ─────────────────────────────────────────────────────────────────

def upsert_team(conn, region: str, sport: str, slug: str, base: str) -> int:
    row = conn.execute("""
        INSERT INTO njcaa_reg_baseball_teams (region, sport, slug, base_url, season)
        VALUES (%s, %s, %s, %s, %s)
        ON CONFLICT (region, sport, slug, season) DO UPDATE SET base_url = EXCLUDED.base_url
        RETURNING id
    """, (region, sport, slug, base, SEASONS[sport])).fetchone()
    return row["id"]


def upsert_player(conn, team_id: int, row: dict) -> int:
    r = conn.execute("""
        INSERT INTO njcaa_reg_baseball_players (team_id, jersey, full_name, position, class_year)
        VALUES (%s, %s, %s, %s, %s)
        ON CONFLICT (team_id, full_name) DO UPDATE SET
            jersey     = COALESCE(EXCLUDED.jersey,     njcaa_reg_baseball_players.jersey),
            position   = COALESCE(EXCLUDED.position,   njcaa_reg_baseball_players.position),
            class_year = COALESCE(EXCLUDED.class_year, njcaa_reg_baseball_players.class_year)
        RETURNING id
    """, (team_id, row.get("jersey"), row["name"], row.get("pos"), row.get("cl"))).fetchone()
    return r["id"]


def upsert_stats(conn, player_id: int, row: dict, season: str):
    conn.execute("""
        INSERT INTO njcaa_reg_baseball_stats (
            player_id, season, g, ab, r, h, doubles, triples, hr,
            rbi, bb, k, sb, cs, avg, obp, slg, ops
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, %s, %s, %s, %s
        )
        ON CONFLICT (player_id, season) DO UPDATE SET
            g=EXCLUDED.g, ab=EXCLUDED.ab, r=EXCLUDED.r, h=EXCLUDED.h,
            doubles=EXCLUDED.doubles, triples=EXCLUDED.triples, hr=EXCLUDED.hr,
            rbi=EXCLUDED.rbi, bb=EXCLUDED.bb, k=EXCLUDED.k,
            sb=EXCLUDED.sb, cs=EXCLUDED.cs,
            avg=EXCLUDED.avg, obp=EXCLUDED.obp, slg=EXCLUDED.slg, ops=EXCLUDED.ops
    """, (
        player_id, season,
        row.get("g"), row.get("ab"), row.get("r"), row.get("h"),
        row.get("doubles"), row.get("triples"), row.get("hr"),
        row.get("rbi"), row.get("bb"), row.get("k"),
        row.get("sb"), row.get("cs"),
        row.get("avg"), row.get("obp"), row.get("slg"), row.get("ops"),
    ))


# ── Core Scrape ───────────────────────────────────────────────────────────────

def scrape_team(conn, region: str, sport: str, slug: str, base: str) -> int:
    season = SEASONS[sport]
    team_page = f"{base}/sports/{sport}/{season}/teams/{slug}"
    url = f"{team_page}?tmpl=brief-category-template&pos=overall&r=0"

    r = fetch(url, base, team_page)
    if not r or r.status_code != 200:
        code = r.status_code if r else "err"
        print(f"      SKIP {slug} [{code}]")
        return 0

    rows = parse_batting_table(r.text)
    if not rows:
        print(f"      SKIP {slug} [no data]")
        return 0

    team_id = upsert_team(conn, region, sport, slug, base)
    saved = 0
    for row in rows:
        if not row["name"]:
            continue
        player_id = upsert_player(conn, team_id, row)
        upsert_stats(conn, player_id, row, season)
        saved += 1

    conn.commit()
    return saved


def get_slugs(sport: str, region: str, base: str, teams_data: dict | None) -> list[str]:
    """Return slugs from JSON if available, else try dynamic discovery."""
    if teams_data and sport in teams_data and region in teams_data[sport]:
        slugs = teams_data[sport][region].get("slugs", [])
        if slugs:
            return slugs

    print(f"    [slug-discover] fetching listing page for {sport}/{region}...")
    slugs = discover_slugs(base, sport, SEASONS[sport])
    if slugs:
        print(f"    [slug-discover] found {len(slugs)} teams")
    else:
        print(f"    [slug-discover] WAF blocked or empty — skipping {region}")
    return slugs


# ── Summary ───────────────────────────────────────────────────────────────────

def print_summary(conn, sport: str):
    row = conn.execute("""
        SELECT COUNT(DISTINCT t.id) AS teams,
               COUNT(DISTINCT p.id) AS players,
               COUNT(s.id)          AS stat_rows
        FROM njcaa_reg_baseball_teams t
        JOIN njcaa_reg_baseball_players p ON p.team_id = t.id
        JOIN njcaa_reg_baseball_stats   s ON s.player_id = p.id
        WHERE t.sport = %s
    """, (sport,)).fetchone()

    label = "Softball" if sport == "sball" else "Baseball"
    print(f"\n  {label} in DB: "
          f"{row['teams']} teams  {row['players']} players  {row['stat_rows']} stat rows")

    # Top hitters by avg (min 30 AB)
    top = conn.execute("""
        SELECT p.full_name, t.slug AS team, t.region,
               s.avg, s.obp, s.slg, s.ops,
               s.h, s.ab, s.hr, s.rbi, s.sb
        FROM njcaa_reg_baseball_stats s
        JOIN njcaa_reg_baseball_players p ON s.player_id = p.id
        JOIN njcaa_reg_baseball_teams   t ON p.team_id = t.id
        WHERE t.sport = %s AND s.ab >= 30
        ORDER BY s.avg DESC NULLS LAST
        LIMIT 5
    """, (sport,)).fetchall()

    if top:
        print(f"\n  Top {label} hitters (min 30 AB):")
        for r in top:
            avg = float(r["avg"]) if r["avg"] else 0
            obp = float(r["obp"]) if r["obp"] else 0
            slg = float(r["slg"]) if r["slg"] else 0
            ops = float(r["ops"]) if r["ops"] else 0
            print(f"    {r['full_name']:<28} {r['team']:<35} [{r['region']}] "
                  f"AVG={avg:.3f} OBP={obp:.3f} SLG={slg:.3f} OPS={ops:.3f} "
                  f"H={r['h']} AB={r['ab']} HR={r['hr']} RBI={r['rbi']} SB={r['sb']}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="NJCAA Regional Baseball/Softball Scraper")
    parser.add_argument("--sport", choices=["sball", "bsb"], default=None,
                        help="Sport to scrape (default: both)")
    parser.add_argument("--region", choices=list(REGIONS.keys()), default=None,
                        help="Only scrape one region")
    args = parser.parse_args()

    # Load hardcoded slugs if available
    teams_data = None
    if TEAMS_JSON.exists():
        with open(TEAMS_JSON) as f:
            teams_data = json.load(f)
        print(f"  Loaded team slugs from {TEAMS_JSON.name}")
    else:
        print(f"  No {TEAMS_JSON.name} — will attempt dynamic slug discovery")

    sports = [args.sport] if args.sport else ["sball", "bsb"]
    region_ids = [args.region] if args.region else list(REGIONS.keys())

    print(f"=== NJCAA Regional Baseball/Softball Scraper ===")
    print(f"  Sports  : {', '.join(sports)}")
    print(f"  Regions : {', '.join(region_ids)}")

    with psycopg.connect(
        host=DB_CONFIG["host"],
        port=DB_CONFIG["port"],
        dbname=DB_CONFIG["dbname"],
        row_factory=psycopg.rows.dict_row,
        autocommit=False,
    ) as conn:
        ensure_schema(conn)

        for sport in sports:
            print(f"\n{'='*60}")
            print(f"  Sport: {'Softball' if sport == 'sball' else 'Baseball'} ({sport})")

            grand_teams = 0
            grand_players = 0

            for i, region in enumerate(region_ids):
                base = REGIONS[region]
                if i > 0:
                    time.sleep(REGION_DELAY)

                slugs = get_slugs(sport, region, base, teams_data)
                if not slugs:
                    print(f"\n  [{region}] SKIP — no slugs available")
                    continue

                print(f"\n  [{region}] {base}  ({len(slugs)} teams)")

                region_players = 0
                for j, slug in enumerate(slugs):
                    n = scrape_team(conn, region, sport, slug, base)
                    if n > 0:
                        print(f"    {j+1:>2}/{len(slugs)} {slug[:38]:<38} {n:>3} players")
                    grand_teams += 1
                    region_players += n
                    if j < len(slugs) - 1:
                        time.sleep(CRAWL_DELAY)

                grand_players += region_players
                print(f"    → {region}: {region_players} players from {len(slugs)} teams")

            print_summary(conn, sport)
            print(f"\n  {sport} run total: {grand_teams} teams, {grand_players} players")


if __name__ == "__main__":
    main()
